### ISSUE TITLE
Can this repo detect the fall in real-time?

### ISSUE THREAD

**Issue by xwr96** [ivineetm007/Fall-detection#2]
Hi! if i want to use camera to detect the human who fall down in real-time, can I use this repo?
thanks

**Comment by ivineetm007** [comment]
The current code is not written for real time detection. You need to make changes in the code. Check out the Demo.ipynb file and the steps to run it. This file contains code for fall detection in offline mode in which the input is the thermal video and the output is the anomaly score at each frame number/time stamps. This code consists of person detection, frames preprocessing, chunking of frames, model prediction and chunk/window level scores to frame level conversion. These steps need to be configured/changed for real time detection.

**Comment by xwr96** [comment]
thanks for your reply! I will I will study it further

**Comment by xwr96** [comment]
hi！I want to consult two question as follows：
1、I follow your readme running the code and find that there will be a false peak when someone goes in and out of the screen. How to solve this problem?

2、If the action is very similar to a fall, such as bending down to pick up things, what to classified them? Can this problem be solved by training a large number of data sets or is there a better solution?
thanks！

**Comment by titubeta** [comment]
1. There could be a false peak when a person enters/leave the scene because of the change in heat. Since this is a thermal camera, it matters. For depth or infra-red/RGB camera this should not be a major issue. However, if a person is half in the scene, you may still get a peak. 
2. At a fundamental level, an anomaly detector is as good as the concept of normal is. If your normal data comprises of bending, picking up things, it is expected that a good detector will learn that as a normal activity over a period of time. If it is not, then it will be detected as an anomaly.  We need to remember that this technique is detecting a fall as an anomaly. Hence, if any unusual behavior is observed that was not seen before (e.g. fainting, multiple people in a scene  (if you trained on single person), crawling etc.), can be detected as an anomaly.

**Comment by mstc-xqp** [comment]
> 1. There could be a false peak when a person enters/leave the scene because of the change in heat. Since this is a thermal camera, it matters. For depth or infra-red/RGB camera this should not be a major issue. However, if a person is half in the scene, you may still get a peak.
> 2. At a fundamental level, an anomaly detector is as good as the concept of normal is. If your normal data comprises of bending, picking up things, it is expected that a good detector will learn that as a normal activity over a period of time. If it is not, then it will be detected as an anomaly.  We need to remember that this technique is detecting a fall as an anomaly. Hence, if any unusual behavior is observed that was not seen before (e.g. fainting, multiple people in a scene  (if you trained on single person), crawling etc.), can be detected as an anomaly.

so how to address the question 2?
And there are another two questions.

If the action is very similar to a fall,  such as stand up. it will cause a false peak too.
If the man is away from the camera（in the side of the pictcure not in the middle ）  The score is not high when the man falls .

Thank u very much!

**Comment by titubeta** [comment]
Short answer - we will have to collect more data and train classifier as to what 'normal' means. And this can vary across people, especially for older adults or people with cognitive/physical impairments.

Stand up is not the same as a fall; however, there can be other similar activities to fall (as I discussed earlier). There is no straightforward answer to handle very similar activities to fall. Perhaps, the only way is to collect large amount of data over a period of time. We must understand that the concept of 'normal' can also change with time.

"If the man is away from the camera（in the side of the pictcure not in the middle ） The score is not high when the man falls."
I don't know what you mean here. When a person is not in full camera view, we may still detect falls. In our DeepFall paper (Section 4.2, https://arxiv.org/pdf/1809.00977.pdf), we showed that even if the fall happens in half of the video frames, we can still detect it. The overall idea of using Autoencoders is that the network is trained on normal activities and will reconstruct them with lower reconstruction error, and any anomaly (e.g. fall) will be reconstructed with large reconstruction error. Therefore, a fall should have a high score / reconstruction error. If that is not the case, then we will miss to detect the fall.

**Comment by mstc-xqp** [comment]
![ea97334b591013cb30276adc9f800cf](https://user-images.githubusercontent.com/19384581/100980683-92ce1f00-3580-11eb-8db0-e852671e22de.png)
hi

as you can see . the “fall” score is lower than  "stand up"  and "enter" score .

it is h

**Comment by titubeta** [comment]
Which data is that? Is it the thermal data used in the paper? You will have to visualize what that particular window is doing. The AUC is approximately 0.9 reported in our paper, which means that the model is not perfect all the time, so missed falls or false alarms may also occur.

**Comment by mstc-xqp** [comment]
No i use my own data. and test it on the dscate3d model and this model  all looks like this.
Some false alarms occur , if i use my own data.

**Comment by titubeta** [comment]
Sorry I cannot comment on your data, you will have to follow the guidelines to define normal data, label and process it. Our models were for thermal and depth camera. I wish you good luck.

**Comment by titubeta** [comment]
One major challenge is to collect large amount of 'normal' data to train the autoencoder, otherwise it will be hard to generalize.

**Comment by mstc-xqp** [comment]
Thank u very much!  I use 3000 photos. Is is too few?

**Comment by titubeta** [comment]
The input to autoencoder is a video sequence (of images) and not single images. In our paper, a video sequence comprised of 8 images. In principle, you would need large amount of data (video sequences) to train a generalizable classifier. Perhaps, 3000 images doesn't seem too large. In our paper, the datasets had 60,000+ (thermal data) and up to 200,000+ (depth data) video sequences.

**Comment by xwr96** [comment]
hi！I want to ask which  xx_train.py can I use to train depth images?becasue I find all the xx_train.py code only contains two formats:thermal and flow. So can i use 3DCAE_train.py to train the depth images?

**Comment by titubeta** [comment]
If you have just one type of data (i.e. videos), then you should go to the [DeepFall ](https://github.com/JJN123/Fall-Detection) github page. The current code (and corresponding paper) combines normal videos and optical flow. Good Luck.
